import mongoose from "mongoose";
import { createSchema, Type, typedModel } from 'ts-mongoose';
import { App1 } from "../app_old";
import UserModel from './UserModel'
// import ImageModel from "./ImageModel";

const PostSchema = createSchema({
  //Add UUID generated by firebase here
  UserId: Type.objectId({ ref: "Users", required: true }),
  Caption: Type.string({ default: "" }),
  Images: [Type.string({ default: "" })],
  Videos: [Type.string({ default: "" })],
  PostedAt: Type.date({ required: true, default: Date.now }),
  ClubId: Type.objectId({ ref: "Clubs", required: true }),
  ClubName: Type.mixed({ required: true }),
  UniversityId: Type.mixed({}),
  UniversityName: Type.string({ required: true }),
});


export default App1.instance.conn.model("Post",PostSchema);;
